# Generated by Django 6.0.5 on 2026-05-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('accountId', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('credenciales', models.CharField(max_length=200)),
                ('fechaIntegracion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='empresa')),
            ],
        ),
    ]
