# Generated by Django 6.0.5 on 2026-05-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precioMensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maxUsuarios', models.IntegerField()),
                ('maxProyectos', models.IntegerField()),
                ('soportePremium', models.BooleanField(default=False)),
                ('analisisAvanzado', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
